const products = [
  {
    "name": "Classic White T-Shirt",
    "category": "Men",
    "brand": "UrbanStyle",
    "price": 599,
    "rating": 4.2,
    "stock": 45,
    "image": "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&auto=format&fit=crop",
    "description": "A minimalist, premium cotton crewneck tee engineered for breathable comfort and a timeless silhouette.",
    "colors": ["Black", "White", "Blue"],
    "sizes": ["S", "M", "L", "XL"],
    "sku": "PRD001"
  },
  {
    "name": "Slim Fit Black Jeans",
    "category": "Men",
    "brand": "DenimCo",
    "price": 1499,
    "rating": 4.3,
    "stock": 30,
    "image": "https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&auto=format&fit=crop",
    "description": "Sleek, stretch-fit denim offering maximum mobility with a tailored, modern finish.",
    "colors": ["Black", "White", "Blue"],
    "sizes": ["S", "M", "L", "XL"],
    "sku": "PRD002"
  },
  {
    "name": "Casual Blue Shirt",
    "category": "Men",
    "brand": "TrendWear",
    "price": 999,
    "rating": 4.4,
    "stock": 40,
    "image": "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&auto=format&fit=crop",
    "description": "Lightweight button-down crafted from breathable linen-blend fabric, perfect for smart-casual weekends.",
    "colors": ["Black", "White", "Blue"],
    "sizes": ["S", "M", "L", "XL"],
    "sku": "PRD003"
  },
  {
    "name": "Floral Summer Dress",
    "category": "Women",
    "brand": "FashionHub",
    "price": 1799,
    "rating": 4.5,
    "stock": 20,
    "image": "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&auto=format&fit=crop",
    "description": "Flowy A-line dress featuring a vibrant botanical print and an adjustable waist tie for sunny days out.",
    "colors": ["Black", "White", "Blue"],
    "sizes": ["S", "M", "L", "XL"],
    "sku": "PRD004"
  },
  {
    "name": "High Waist Jeans",
    "category": "Women",
    "brand": "DenimCo",
    "price": 1599,
    "rating": 4.6,
    "stock": 35,
    "image": "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&auto=format&fit=crop",
    "description": "Classic high-rise fit denim hugging the waist perfectly while keeping things effortlessly retro.",
    "colors": ["Black", "White", "Blue"],
    "sizes": ["S", "M", "L", "XL"],
    "sku": "PRD005"
  },
  {
    "name": "Women's Hoodie",
    "category": "Women",
    "brand": "UrbanStyle",
    "price": 1299,
    "rating": 4.7,
    "stock": 28,
    "image": "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600&auto=format&fit=crop",
    "description": "Ultra-soft fleece hoodie featuring a relaxed fit drop-shoulder layout and spacious front kanga pocket.",
    "colors": ["Black", "White", "Blue"],
    "sizes": ["S", "M", "L", "XL"],
    "sku": "PRD006"
  },
  {
    "name": "Running Shoes",
    "category": "Footwear",
    "brand": "SportX",
    "price": 2499,
    "rating": 4.8,
    "stock": 50,
    "image": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop",
    "description": "High-performance mesh trainers equipped with responsive foam cushioning for superior energy return.",
    "colors": ["Black", "White", "Blue"],
    "sizes": ["S", "M", "L", "XL"],
    "sku": "PRD007"
  },
  {
    "name": "Leather Sneakers",
    "category": "Footwear",
    "brand": "StepUp",
    "price": 2799,
    "rating": 4.1,
    "stock": 25,
    "image": "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&auto=format&fit=crop",
    "description": "Sleek low-top sneakers crafted from genuine premium leather with a durable vulcanized rubber sole.",
    "colors": ["Black", "White", "Blue"],
    "sizes": ["S", "M", "L", "XL"],
    "sku": "PRD008"
  },
  {
    "name": "Sports Watch",
    "category": "Accessories",
    "brand": "TimeX",
    "price": 1999,
    "rating": 4.2,
    "stock": 18,
    "image": "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=600&auto=format&fit=crop",
    "description": "Rugged, water-resistant multi-function sports watch built with an integrated lap timer and backlighting.",
    "colors": ["Black", "White", "Blue"],
    "sizes": ["S", "M", "L", "XL"],
    "sku": "PRD009"
  },
  {
    "name": "Leather Wallet",
    "category": "Accessories",
    "brand": "Classic",
    "price": 799,
    "rating": 4.3,
    "stock": 60,
    "image": "https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&auto=format&fit=crop",
    "description": "Slim bifold genuine leather wallet sporting built-in RFID blocking and 6 tailored card slots.",
    "colors": ["Black", "White", "Blue"],
    "sizes": ["S", "M", "L", "XL"],
    "sku": "PRD010"
  },
  {
    "name": "Wireless Earbuds",
    "category": "Electronics",
    "brand": "SoundPro",
    "price": 2999,
    "rating": 4.4,
    "stock": 22,
    "image": "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop",
    "description": "True wireless ergonomic earbuds packing active noise cancellation and crisp signature stereo bass.",
    "colors": ["Black", "White", "Blue"],
    "sizes": ["S", "M", "L", "XL"],
    "sku": "PRD011"
  },
  {
    "name": "Smart Watch",
    "category": "Electronics",
    "brand": "TechFit",
    "price": 4999,
    "rating": 4.5,
    "stock": 15,
    "image": "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&auto=format&fit=crop",
    "description": "Next-gen smart wearable boasting dynamic AMOLED touch display alongside 24/7 heart-rate and SpO2 tracking.",
    "colors": ["Black", "White", "Blue"],
    "sizes": ["S", "M", "L", "XL"],
    "sku": "PRD012"
  },
  {
    "name": "Laptop Backpack",
    "category": "Bags",
    "brand": "TravelPro",
    "price": 1499,
    "rating": 4.6,
    "stock": 45,
    "image": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop",
    "description": "Water-repellent heavy-duty backpack with a dedicated padded compartment for laptops up to 15.6 inches.",
    "colors": ["Black", "White", "Blue"],
    "sizes": ["S", "M", "L", "XL"],
    "sku": "PRD013"
  },
  {
    "name": "Travel Duffel Bag",
    "category": "Bags",
    "brand": "TravelPro",
    "price": 1899,
    "rating": 4.7,
    "stock": 30,
    "image": "https://images.unsplash.com/photo-1547949003-9792a18a2601?w=600&auto=format&fit=crop",
    "description": "Spacious weekend duffel bag built from rugged canvas trim featuring a dynamic shoe isolation pouch.",
    "colors": ["Black", "White", "Blue"],
    "sizes": ["S", "M", "L", "XL"],
    "sku": "PRD014"
  },
  {
    "name": "Cotton Polo T-Shirt",
    "category": "Men",
    "brand": "UrbanStyle",
    "price": 899,
    "rating": 4.8,
    "stock": 55,
    "image": "https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=600&auto=format&fit=crop",
    "description": "Crisp piqué knit cotton polo shirt sporting a structured collar and refined minimalist branding.",
    "colors": ["Black", "White", "Blue"],
    "sizes": ["S", "M", "L", "XL"],
    "sku": "PRD015"
  },
  {
    "name": "Formal White Shirt",
    "category": "Men",
    "brand": "TrendWear",
    "price": 1299,
    "rating": 4.1,
    "stock": 35,
    "image": "https://images.unsplash.com/photo-1603252109303-2751441dd157?w=600&auto=format&fit=crop",
    "description": "Wrinkle-resistant luxury dress shirt engineered for corporate styling and a clean tapered profile.",
    "colors": ["Black", "White", "Blue"],
    "sizes": ["S", "M", "L", "XL"],
    "sku": "PRD016"
  },
  {
    "name": "Women's Handbag",
    "category": "Women",
    "brand": "FashionHub",
    "price": 1999,
    "rating": 4.2,
    "stock": 25,
    "image": "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&auto=format&fit=crop",
    "description": "Structured vegan leather tote bag fitted with an organized gold-zipper split inner core layout.",
    "colors": ["Black", "White", "Blue"],
    "sizes": ["S", "M", "L", "XL"],
    "sku": "PRD017"
  },
  {
    "name": "Summer Top",
    "category": "Women",
    "brand": "FashionHub",
    "price": 799,
    "rating": 4.3,
    "stock": 40,
    "image": "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=600&auto=format&fit=crop",
    "description": "Breezy and light sleeveless blouse optimal for layering or wearing standalone during coastal getaways.",
    "colors": ["Black", "White", "Blue"],
    "sizes": ["S", "M", "L", "XL"],
    "sku": "PRD018"
  },
  {
    "name": "Bluetooth Speaker",
    "category": "Electronics",
    "brand": "SoundPro",
    "price": 2499,
    "rating": 4.4,
    "stock": 18,
    "image": "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&auto=format&fit=crop",
    "description": "IPX7 waterproof portable Bluetooth speaker projecting immersive 360-degree bass and 12-hour playback.",
    "colors": ["Black", "White", "Blue"],
    "sizes": ["S", "M", "L", "XL"],
    "sku": "PRD019"
  },
  {
    "name": "Gaming Mouse",
    "category": "Electronics",
    "brand": "TechFit",
    "price": 1499,
    "rating": 4.5,
    "stock": 38,
    "image": "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&auto=format&fit=crop",
    "description": "Ergonomic gaming mouse boasting an adjustable 16,000 DPI optical sensor and full dynamic RGB backlighting.",
    "colors": ["Black", "White", "Blue"],
    "sizes": ["S", "M", "L", "XL"],
    "sku": "PRD020"
  },
  {
    "name": "Baseball Cap",
    "category": "Accessories",
    "brand": "UrbanStyle",
    "price": 499,
    "rating": 4.6,
    "stock": 75,
    "image": "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=600&auto=format&fit=crop",
    "description": "Classic 6-panel cotton twill strapback cap offering dynamic sun protection with a structured curved visor.",
    "colors": ["Black", "White", "Blue"],
    "sizes": ["S", "M", "L", "XL"],
    "sku": "PRD021"
  },
  {
    "name": "Sunglasses",
    "category": "Accessories",
    "brand": "Classic",
    "price": 999,
    "rating": 4.7,
    "stock": 30,
    "image": "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&auto=format&fit=crop",
    "description": "Polarized retro-style aviator sunglasses with UV400 protective scratch-resistant dark lenses.",
    "colors": ["Black", "White", "Blue"],
    "sizes": ["S", "M", "L", "XL"],
    "sku": "PRD022"
  },
  {
    "name": "Men's Winter Jacket",
    "category": "Men",
    "brand": "UrbanStyle",
    "price": 2499,
    "rating": 4.8,
    "stock": 20,
    "image": "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&auto=format&fit=crop",
    "description": "Insulated heavy-duty puffer jacket utilizing synthetic down tech to ensure supreme warmth in sub-zero weather.",
    "colors": ["Black", "White", "Blue"],
    "sizes": ["S", "M", "L", "XL"],
    "sku": "PRD023"
  },
  {
    "name": "Women's Cardigan",
    "category": "Women",
    "brand": "FashionHub",
    "price": 1499,
    "rating": 4.1,
    "stock": 30,
    "image": "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=600&auto=format&fit=crop",
    "description": "Cozy, open-front knit cardigan featuring ribbed cuffs and cozy side drop-in storage pockets.",
    "colors": ["Black", "White", "Blue"],
    "sizes": ["S", "M", "L", "XL"],
    "sku": "PRD024"
  },
  {
    "name": "Formal Leather Shoes",
    "category": "Footwear",
    "brand": "StepUp",
    "price": 2999,
    "rating": 4.2,
    "stock": 22,
    "image": "https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=600&auto=format&fit=crop",
    "description": "Hand-stitched genuine leather Oxford dress shoes featuring elegant toe-cap brogue detailing.",
    "colors": ["Black", "White", "Blue"],
    "sizes": ["S", "M", "L", "XL"],
    "sku": "PRD025"
  },
  {
    "name": "Canvas Shoes",
    "category": "Footwear",
    "brand": "StepUp",
    "price": 1599,
    "rating": 4.3,
    "stock": 40,
    "image": "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=600&auto=format&fit=crop",
    "description": "Everyday casual low-top lace-up canvas sneakers with a flexible non-slip honeycomb traction outer sole.",
    "colors": ["Black", "White", "Blue"],
    "sizes": ["S", "M", "L", "XL"],
    "sku": "PRD026"
  },
  {
    "name": "Power Bank 20000mAh",
    "category": "Electronics",
    "brand": "TechFit",
    "price": 1799,
    "rating": 4.4,
    "stock": 28,
    "image": "https://images.unsplash.com/photo-1609592424109-dd9892f1b177?w=600&auto=format&fit=crop",
    "description": "Ultra-high capacity power bank supporting 22.5W fast charging equipped with dual USB-A and Type-C delivery hubs.",
    "colors": ["Black", "White", "Blue"],
    "sizes": ["S", "M", "L", "XL"],
    "sku": "PRD027"
  },
  {
    "name": "Travel Neck Pillow",
    "category": "Travel",
    "brand": "TravelPro",
    "price": 699,
    "rating": 4.5,
    "stock": 50,
    "image": "https://images.unsplash.com/photo-1520116468816-95b69f847357?w=600&auto=format&fit=crop",
    "description": "Ergonomic high-density memory foam neck pillow enclosed within a removable plush washable velour skin.",
    "colors": ["Black", "White", "Blue"],
    "sizes": ["S", "M", "L", "XL"],
    "sku": "PRD028"
  },
  {
    "name": "Gym Water Bottle",
    "category": "Fitness",
    "brand": "SportX",
    "price": 399,
    "rating": 4.6,
    "stock": 80,
    "image": "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&auto=format&fit=crop",
    "description": "BPA-free leakproof sports bottle featuring a quick-access flip top straw mechanism and structural volume markings.",
    "colors": ["Black", "White", "Blue"],
    "sizes": ["S", "M", "L", "XL"],
    "sku": "PRD029"
  },
  {
    "name": "Yoga Mat",
    "category": "Fitness",
    "brand": "SportX",
    "price": 999,
    "rating": 4.7,
    "stock": 35,
    "image": "https://images.unsplash.com/photo-1592432678016-e910b452f9a2?w=600&auto=format&fit=crop",
    "description": "Eco-friendly, 6mm thick anti-tear TPE cushioning mat ensuring non-slip floor traction for intense workouts.",
    "colors": ["Black", "White", "Blue"],
    "sizes": ["S", "M", "L", "XL"],
    "sku": "PRD030"
  }
];


export default products;